[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
nalgebra = "0.32"
gltf = "1.4"
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "WebGl2RenderingContext",
    "WebGlProgram",
    "WebGlShader",
    "WebGlBuffer",
    "WebGlUniformLocation",
    "console",
    "WebGlTexture",
    "HtmlImageElement",
    "ImageBitmap",
    "ImageBitmapOptions",
    "ImageOrientation",
    "Blob",
    "Request",
    "RequestInit",
    "Response",
    "ExtTextureFilterAnisotropic",
] }
kira = "0.11.0"
