[package]
name = "app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
engine = { path = "../engine" }
tinycraft = { path = "../projects/tinycraft" }
solar_system = { path = "../projects/solar_system" }
crossy_road = { path = "../projects/crossy_road" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "WebGlRenderingContext",
    "KeyboardEvent",
    "MouseEvent",
    "WheelEvent",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Headers",
] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["--enable-reference-types", "-O"]
