[package]
name = "tinycraft"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "../../engine" }
wasm-bindgen = "0.2"
nalgebra = "0.32"
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "Element",
    "console",
    "HtmlInputElement",
    "WebGlTexture",
    "WebGlRenderingContext",
] }
kira = "0.11.0"
js-sys = "0.3.83"
